version: '3'

services:
  mongodb:
    container_name: buffyverse-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_PASSWORD: buffyverse-pass
      MONGO_INITDB_ROOT_USERNAME: buffyverse-user
      MONGO_INITDB_DATABASE: buffyverse
    ports:
      - 27017:27017